version: '3.5'
services:
  ownership-server:
    image: quay.io/decentraland/ownership-server:${DOCKER_TAG:-latest}
    working_dir: /app
    restart: always
    environment:
      - HTTP_SERVER_PORT=1234
    env_file:
      - .env
    expose:
      - "1234"
    network_mode:
      "host"

  nginx:
    container_name: nginx
    image: nginx:1.25-alpine
    ports:
      - "80:80"
      - "443:443"
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    volumes:
      - ./local/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./local/nginx/conf.d:/etc/nginx/conf.d
      - ./local/nginx/include:/etc/nginx/include
      - ./local/nginx/html:/etc/nginx/html
      - ./local/certbot/conf:/etc/letsencrypt
      - ./local/certbot/www:/var/www/certbot
    restart: always
    depends_on:
      - certbot
      - ownership-server
    logging:
      driver: syslog
      options: { tag: nginx }
    network_mode:
      "host"

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: always
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./local/certbot/conf:/etc/letsencrypt
      - ./local/certbot/www:/var/www/certbot
    logging:
      driver: syslog
      options: { tag: certbot }
    network_mode:
      "host"
